add rust benchmark
linksplatform/Comparisons.PostgreSQLVSDoublets pull request #6
Opened 2022-05-29 15:43 UTC by Mitron57

2022-06-05 08:55 UTC, uselessgoddess requested changes

2022-07-02 11:22 UTC, uselessgoddess reviewed
It's very hard to review

2022-07-02 11:22 UTC, uselessgoddess commented on rust/benches/bench.rs
> +async fn connect() -> Client {
Please, handle errors

2022-07-02 11:22 UTC, uselessgoddess commented on rust/benches/bench.rs
> +            eprintln!("Connection error: {}", err);
return Error

2022-07-02 11:22 UTC, uselessgoddess commented on rust/src/lib.rs
> +mod linkstransaction;
Preifix? Why?

2022-07-02 11:22 UTC, uselessgoddess commented on rust/src/linksclient.rs
> +                        &[],
Later use sql builder

2022-07-02 11:22 UTC, uselessgoddess commented on rust/src/linksclient.rs
> +            [] | [_, ..] => eprintln!("Constraints violation, use \"any\""),
```suggestion
            [] | [_, ..] => panic!("Constraints violation, use \"any\""),
```

2022-07-03 20:24 UTC, Mitron57 commented on rust/src/linksclient.rs
> +                        &[],
Thanks for advice!

2022-07-07 11:07 UTC, uselessgoddess commented on rust/benches/bench.rs
> -            let mut client = connect().await;
Why new connection?

2022-07-07 11:07 UTC, uselessgoddess commented on rust/src/lib.rs
> +pub use links_transaction::Transaction;
```suggestion
pub use client::Client;
pub use transaction::Transaction;
```

2022-07-07 11:07 UTC, uselessgoddess commented on rust/src/links_client.rs
> +            [] | [_, ..] => panic!("Constraints violation, use \"any\" "),
```suggestion
            [] | [_, ..] => panic!("Constraints violation, use `any`"),
```

2022-07-07 11:07 UTC, uselessgoddess commented on rust/src/links_transaction.rs
>          self.0
Please, use non-tuple struct

2022-07-07 17:56 UTC, Mitron57 commented on rust/src/links_transaction.rs
>          self.0
But you said me to do so... Well, ok

2023-08-21 15:06 UTC, merged

2023-08-21 15:43 UTC, uselessgoddess reviewed
Nuh uh

2023-08-21 15:43 UTC, uselessgoddess commented on rust/benches/create.rs
> +#![feature(allocator_api)]
Rust require features only in `lib.rs`/`main.rs`

2023-08-21 15:43 UTC, uselessgoddess commented on rust/benches/create.rs
> +pub fn create_links(c: &mut Criterion) -> Result<(), Box<dyn Error>> {
Better use [global alias like this](https://doc.rust-lang.org/std/io/type.Result.html) or [`anyhow::Result`](https://docs.rs/anyhow/latest/anyhow/struct.Result.html)

2023-08-21 15:43 UTC, uselessgoddess commented on rust/benches/create.rs
> +    let allocator = std::alloc::Global;
Oh bro. Useless let binding

2023-08-21 15:43 UTC, uselessgoddess commented on rust/benches/create.rs
> +        let _ = client.setup();
Why not just do something like this:
```rust
trait Benched {
    type Builder;
    
    fn setup(builder: Self::Builder) -> Self;
    fn bench(b: &mut Bencher);
}

// possible implementation
struct Fib;

impl Benched for Fib {
    type Builder = Fib;

    fn setup(builder: Self::Builder) -> Self { builder  }
    fn bench(b: &mut Bencher) { ... }
}

struct FibMemo<const N: usize>([u64; N]);

impl Benched for FibMemo<N> {
    type Builder = [u64; N];

    fn setup(builder: Self::Builder) -> Self { ...  }
    fn bench(b: &mut Bencher) { ... }
}
```
Instead of manually ugly implementation

2023-08-21 15:43 UTC, uselessgoddess commented on rust/src/transaction.rs
> +impl<T: LinkType> Links<T> for Transaction<'_, T> {
Why implement this if it's not used in the generalized test for `Doublets` anyway?

2023-08-21 15:43 UTC, uselessgoddess commented on rust/src/client.rs
> +            self.runtime.block_on(self.client.transaction())?,
It is a bad practise (very bad...). 
Better use: 
```rust
rt.block_on(async move {
    // sync sync sync 
    .await!!!
    // sync sync sync 
    // . . . 
    .await!!!
    // . . . 
})
```
Instead of silent `block_on`s

2023-08-21 15:43 UTC, uselessgoddess commented on rust/src/lib.rs
> +}
This macro is trying to be crazy. It's worth keeping just the first overload. 
And that's to simplify the matching

2023-08-21 16:01 UTC, Mitron57 commented on rust/benches/create.rs
> +        let _ = client.setup();
Looks great, thanks!

2023-08-21 16:07 UTC, Mitron57 commented on rust/src/transaction.rs
> +impl<T: LinkType> Links<T> for Transaction<'_, T> {
That's supposed to make benchmarks equal to each other, just copying behavior of preparations before every benchmark, but here I guess, I can just remove this and use implementation above for `Client`

2023-08-21 16:10 UTC, Mitron57 commented on rust/benches/create.rs
> +#![feature(allocator_api)]
I know, but in `benches` directory there is no `main.rs` or `lib.rs`, how can I do that?

2023-08-22 11:37 UTC, uselessgoddess commented on rust/benches/create.rs
> +    let allocator = std::alloc::Global;
Because it 
```rust
struct Foo;

let foo = Foo;
bar(foo);
```
Is similar for:
```rust
bar(Foo);
```

2023-08-22 11:39 UTC, uselessgoddess commented on rust/src/client.rs
> +            self.runtime.block_on(self.client.transaction())?,
Yes one global `async move` block or [`AsyncBencher`](https://docs.rs/criterion/latest/criterion/struct.AsyncBencher.html)